### ISSUE TITLE
Change expected test files to use XLSX instead of CSV

### ISSUE THREAD

**Issue by cathbar** [ProjectDrawdown/solutions#360] opened 2021-07-25 22:17 UTC
There were many problems with numbers being truncated and losing precision in the csv files within `expected.zip`.  This loss in precision causes a whole lot of mismatched numbers in the unit tests. Using an excel workbook format instead of CSVs should preserve the precision. The unit test executor should be updated to handle both XLSX while still maintain backwards compatibility for CSVs.

**Comment by denised** [comment] 2021-08-02 03:29
This was an excellent find and an excellent idea, but having found the root cause of the problem in the VB, I decided instead to continue with (corrected) CSV files instead.  Fixed in commit a1c5e26c64e9b2.

**Closed by denised** 2021-08-02 03:29 UTC
