### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by FranzEricSchneider** [ProjectDrawdown/solutions#73] opened 2020-03-16 00:41 UTC
A friend (@rifkinni) and I are excited to try and get clones of this repository up and running. We're trying to follow the install instructions in Getting Started on the README, but are having some trouble with Jupyter. In a couple of places, for example `ModelHealth.ipynb`, we are getting the error `Error displaying widget: model not found`. This is when trying to view all of the model health graphs. For what it's worth it happened when following the setup instructions both on a fresh Ubuntu 18.04 and on a mac.

Example:
![Screenshot from 2020-03-15 12-21-56](https://user-images.githubusercontent.com/3709527/76713961-b1427080-66fa-11ea-8484-01f587990c85.png)

The offending passage (in the first chunk of `ModelHealth.ipynb`) is this `ipywidgets` call. When commenting that out and refreshing the Jupyter tab the error does not occur. Seems like this could implicate the `ipywidgets` call or any of the objects being passed into it.
```
ipywidgets.VBox([
    ipywidgets.HBox([soln_count_fig, pds_adoption_fig, ref_adoption_fig]),
    scenarios_per_solution_chart,
    ipywidgets.HBox([tam_regional_nonzero_fig, tam_regional_chart]),
    ipywidgets.HBox([ad_regional_nonzero_fig, ad_regional_chart]),
    r2_value_chart,
])
```

Talked with @DentonGentry a bit and bqplot may be a suspect as Jupyterlab went to 1.0. Following the installation instructions we ended up with bqplot version 0.12.5. @DentonGentry mentioned he was using version 0.11.6, so we changed `requirements.txt` to require `bqplot==0.11.6` and reran `pip install -r requirements.txt`. It downgraded the version correctly (confirmed in the Jupyter code), but we still get `Error displaying widget: model not found`.

**Comment by DentonGentry** [comment] 2020-03-16 00:47
Ok, so the issue is not related to the bqplot version. It is odd that the one ipywidgets VBox is having the problem, there are other uses of ipywidgets and bqplot on the page which apparently are unaffected.

**Comment by eschneider1992** [comment] 2020-03-16 02:24
Sometimes it will also wait indefinitely saying "Loading". I gave it ~5 minutes once.
![Screenshot from 2020-03-15 21-17-39](https://user-images.githubusercontent.com/3709527/76717943-97f5f000-670b-11ea-809a-d6a8deda3f23.png)

**Comment by eschneider1992** [comment] 2020-03-17 21:44
Found some interesting things. First, the bqplot tutorials also fail for me. Second, it fails for `jupyter lab` but not for `jupyter notebook`, in the same pipenv shell.
```
(solutions) solutions $ jupyter lab ./jupyter-test.ipynb
```
![Screenshot from 2020-03-17 17-40-19](https://user-images.githubusercontent.com/3709527/76904682-d65bee00-6876-11ea-8fb4-25d2f1a83e53.png)
```
(solutions) solutions $ jupyter notebook ./jupyter-test.ipynb
```
![Screenshot from 2020-03-17 17-41-07](https://user-images.githubusercontent.com/3709527/76904713-e4aa0a00-6876-11ea-9416-88183fd5de64.png)

Example taken from here: https://bqplot.readthedocs.io/en/latest/usage.html#examples

**Comment by eschneider1992** [comment] 2020-03-17 21:46
I don't know much about Jupyter, and am not very familiar with the lab/notebook differences. This looks like it may be a related issue? Does anyone know a `bqplot` js version that worked, in contrast to the python version that we've confirmed (0.11.6)?

**Comment by eschneider1992** [comment] 2020-03-17 21:49
Here are my results for `bqplot`, looks like I've got python 0.11.6 and js 0.5.5
```
(solutions) solutions $ pip show bqplot
Name: bqplot
Version: 0.11.6
Summary: Interactive plotting for the Jupyter notebook, using d3.js and ipywidgets.
Home-page: https://github.com/bloomberg/bqplot
Author: The BQplot Development Team
Author-email: UNKNOWN
License: Apache
Location: /home/eric/.local/share/virtualenvs/solutions-BFrQ741t/lib/python3.8/site-packages
Requires: traitlets, pandas, traittypes, numpy, ipywidgets
Required-by: 
(solutions) solutions $ jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /home/eric/.local/share/virtualenvs/solutions-BFrQ741t/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        bqplot v0.5.5  enabled  OK
        ipyvolume v0.5.2  enabled  OK
        jupyter-threejs v2.1.1  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK
        qgrid v1.1.1  enabled  OK
```

**Comment by denised** [comment] 2021-07-18 21:31
Closing because we've moved away from a widget-oriented solution.  (But thank you for all your investigation @FranzEricSchneider!)

**Closed by denised** 2021-07-18 21:31 UTC
